name: Todo CI
on:
  push:
    branches:
      - "master"
      - "back_connection"
  pull_request:
    branches:
      - "master"

jobs:
  build_android:
    name: Test and build for Android
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2 
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Check code formatting
        run: dart format .
      - name: Run linter
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Build Apk
        run: flutter build apk --target=lib/main_prod_flavor.dart
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk 
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APPID }}
          token: ${{ secrets.TOKEN }}
          groups: pre-testers
          file: build/app/outputs/flutter-apk/app-release.apk



  build-ios:
    name: Build for iOS
    runs-on: macos-latest
      
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS
        run: flutter build ios --no-codesign --target=lib/main_prod_flavor.dart