name: Todo CI
on:
  push:
    branches:
      - "master"
      - "back_connection"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2 
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          dart-sdk: stable
      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Check code formatting
        run: dart format .
      - name: Run linter
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Build Apk
        run: flutter build apk